#!/usr/bin/env python3

import os
import subprocess
import sys
import random
import argparse
import shutil
from distutils import util


parser = argparse.ArgumentParser(description='Stabilizer Compiler Driver')

# Which randomizations should be run
parser.add_argument('-R', action='append', choices=['code', 'heap', 'stack', 'link'], default=[])

# Driver control arguments
parser.add_argument('-v', action='store_true')
parser.add_argument('-lang', choices=['c', 'c++', 'fortran'])
parser.add_argument('-platform', choices=['auto', 'linux', 'osx'], default='auto')
parser.add_argument('-frontend', choices=['gcc', 'clang'], default='clang')

# Compiler pass-through arguments
parser.add_argument('-c', action='store_true')
parser.add_argument('-o')
# NOTE: default to the standard opt -O2 pipeline.
# For code randomization, we also preserve text relocations in the final binary
# so the Stabilizer runtime can fix up remaining pc-relative references (e.g.,
# constant pools) after moving code.
parser.add_argument('-O', type=int, default=2)
parser.add_argument('-g', action='store_true')
parser.add_argument('-f', action='append', default=[])
parser.add_argument('-D', action='append', default=[])
parser.add_argument('-L', action='append', default=[])
parser.add_argument('-I', action='append', default=[])
parser.add_argument('-l', action='append', default=[])
parser.add_argument('input', nargs='+')

# Do the parse
args = parser.parse_args()

if args.frontend == 'gcc':
	print('GCC/DragonEgg frontend is no longer supported. Use -frontend=clang (C/C++) or -lang=fortran (Flang).')
	exit(1)

def run(cmd):
	if args.v:
		print(cmd)
	subprocess.check_call(cmd, shell=True)

def try_run(cmd):
	if args.v:
		print(cmd)
	return subprocess.call(cmd, shell=True) == 0

def require_flang():
	if not FLANG:
		print('Fortran requested but flang was not found. Ensure `flang` (or `flang-new`) is in PATH.')
		exit(1)
	return FLANG


def getPlatform():
	if util.get_platform().startswith('macosx'):
		return 'osx'
	elif util.get_platform().startswith('linux'):
		return 'linux'
	else:
		print('Unsupported platform')
		exit(2)

def arg(flag, values):
	if not isinstance(values, list):
		values = [values]

	cmd = ''
	for v in values:
		if v == True:
			cmd += ' -' + flag
		elif v == False:
			pass
		else:
			cmd += ' -' + flag + v
	return cmd

if args.platform == 'auto':
	args.platform = getPlatform()

STABILIZER_HOME = os.path.dirname(__file__)

if args.platform == 'osx':
	LIBSUFFIX = 'dylib'
	args.frontend = 'clang'
else:
	LIBSUFFIX = 'so'

FLANG = shutil.which('flang') or shutil.which('flang-new')

opts = []
passes = []
stabilize_opts = []

args.l.append('stdc++')
args.l.append('m')
# args.v = True

if 'code' in args.R:
	passes.append('lower-intrinsics')
	passes.append('lower-switch')
	passes.append('lower-invoke')
	stabilize_opts.append('stabilize-code')

if 'stack' in args.R:
	stabilize_opts.append('stabilize-stack')

if 'heap' in args.R:
	stabilize_opts.append('stabilize-heap')

if 'code' in args.R or 'heap' in args.R or 'stack' in args.R:
	args.L.append(STABILIZER_HOME)
	args.l.append('stabilizer')
	passes.append('stabilize')

def compile(input):
	if input.endswith('.o'):
		return input

	if args.lang == 'fortran':
		flang = require_flang()
		common = arg('g', args.g) + arg('I', args.I) + arg('f', args.f) + arg('D', args.D)
		out = arg('o ', args.o)
		src = ' ' + input

		# Emit LLVM bitcode via flang. Try O0 first; fall back if needed.
		for opt in ['0', '1']:
			if try_run(flang + ' -O' + opt + ' -c -emit-llvm' + out + common + src):
				return args.o

		# Last resort: emit LLVM IR assembly and assemble it.
		ll = args.o + '.ll'
		run(flang + ' -O1 -S -emit-llvm' + arg('o ', ll) + common + src)
		run('llvm-as -o ' + args.o + ' ' + ll)

	else:
		# Clang adds `optnone` at -O0, which prevents later `opt` passes
		# (including `default<O*>` and lowering passes) from running. That
		# breaks Stabilizer's assumptions (e.g., we rely on switch lowering to
		# avoid jump tables). Disable that behavior.
		cmd = args.frontend + ' -O0 -Xclang -disable-O0-optnone -c -emit-llvm'
		cmd += arg('o ', args.o)
		cmd += arg('g', args.g)
		cmd += arg('I', args.I)
		cmd += arg('f', args.f)
		cmd += arg('D', args.D)
		cmd += ' ' + input

		run(cmd)

	return args.o

def link(inputs):
	cmd = 'llvm-link -o ' + args.o + '.bc '

	if 'link' in args.R:
		random.shuffle(inputs)

	cmd += ' '.join(inputs)

	run(cmd)
	return args.o + '.bc'

def transform(input):
	cmd = 'opt -o ' + args.o + '.opt.bc'
	cmd += ' ' + input

	cmd += ' --load-pass-plugin=' + STABILIZER_HOME + '/LLVMStabilizer.' + LIBSUFFIX

	cmd += ' -passes=\''

	pipeline = []
	if args.O > 0:
		pipeline.append('default<O' + str(args.O) + '>')

	pipeline.extend(passes)
	cmd += ','.join(pipeline)
	cmd +=  '\''

	cmd += ' '.join([' -' + v + '=true' for v in stabilize_opts])

	run(cmd)
	return args.o + '.opt.bc'

def codegen(input):
	# cmd = 'llc -O0 -relocation-model=pic -disable-fp-elim'
	cmd = 'llc -O0 -relocation-model=pic --frame-pointer=all'
	# Emit a native object file and link it directly. Flang's driver currently
	# does not accept assembly (`.s`) inputs (it can error with "unknown
	# integrated tool '-cc1as'"), so avoid producing/linking `.s` here.
	llc_obj = args.o + '.llc.o'
	cmd += ' -filetype=obj'
	cmd += ' -o ' + llc_obj
	cmd += ' ' + input

	run(cmd)

	if args.lang == 'fortran':
		flang = require_flang()
		cmd = flang
	else:
		cmd = args.frontend

	cmd += ' ' + llc_obj

	# Keep relocation records so the runtime can patch pc-relative references
	# after moving code.
	if args.platform == 'linux' and 'code' in args.R:
		cmd += ' -Wl,--emit-relocs'

	cmd += arg('o ', args.o)
	cmd += arg('f', args.f)
	cmd += arg('L', args.L)
	cmd += arg('l', args.l)

	run(cmd)

	# Avoid leaving extra native objects behind. Keep intermediates only with -v.
	if not args.v:
		try:
			os.unlink(llc_obj)
		except OSError:
			pass

	return args.o

# Build up program arguments
object_files = list(map(compile, args.input))

if not args.c:
	linked = link(object_files)
	transformed = transform(linked)
	codegen(transformed)

